### ISSUE TITLE
Question: Recieving xAP

### ISSUE THREAD

**Issue by PerMalmberg** [antsman/node-red-contrib-xap#2]
Hi,

Am I correct in that this package doesn't support receiving xAP messages? If so, any plans to implement such functionality?

**Comment by antsman** [comment]
Hi Per,

You are right, there is sending side only for now.  Planning to look into receiver (listener/viewer) when more into autumn/winter ;) side of year again.
My own solution for similar need today is xAP hub > xAP to mqtt applet > mqtt in node.

BR, Aivo

**Comment by PerMalmberg** [comment]
Ok, thanks.
